### ISSUE TITLE
python 파일 실행 위치 통일

### ISSUE THREAD

**Issue by MinSikSon** [MinSikSon/idiotquant#13]
1. idiotquant 폴더 내의 모듈은 idiotquant 내에서 실행하도록 구현되어 있음.
2. interface 폴더 내의 모듈은 root 기준으로 실행하도록 구현되어 있음.

*** 파일 실행 위치 통일해야 할 듯 함.

**Comment by ohdoking** [comment]
in main.py

1. 종목 리스트 가져오기
2. 알고리즘 실행시키기 함수를 만들자

**Comment by MinSikSon** [comment]
https://github.com/MinSikSon/idiotquant/tree/feature/13-moved-execution-location-to-main
위 branch 에 main.py 에서 idiotquant 실행하는 sample code 짜보았습니다.
*** 이렇게 하자는 것은 아니고, 한 가지 방법을 생각해본 것임 ***

# 추가사항 설명
## 1 변경점
1. abc (abtract class) 모듈을 사용해서 ```idiotquant\custom_function.py``` 에 추상클래스 AbstractCustomFunction 를 두었습니다. 전략 추가 시에 AbstractCustomFunction 를 상속하는 클래스를 별도로 구현한 뒤, ```idiotquant\custom_function.py``` 의 customFunction 라는 List 에 신규 함수를 추가해야 합니다.
```python
customFunction = [
		CustomFunction__sample,
		CustomFunction__NCAV_strategy,
		CustomFunction__sample2
	]
```
그리고 main.py 도 아래와 같이 수정해주세요.
```python
    parser.add_argument('--select-strategy', '-s', type=int, help='0: sample_1, 1: NCAV 전략, 2: sample_2', required=True)
```
에서 아래와 괄호 부분을 추가
```python
    parser.add_argument('--select-strategy', '-s', type=int, help='0: sample_1, 1: NCAV 전략, 2: sample_2 (, 3: 신규전략)', required=True)
```
## 2 실행
argparse 모듈을 사용하였습니다. main.py 실행 시에 전략을 선택하여 실행할 수 있습니다.

```
(root 에서)
python3 main.py -h
python3 main.py -y 2020 -q 3 -s1
```
