### ISSUE TITLE
종목 리스트 lastest.json 파일 만들기

### ISSUE THREAD

**Issue by ohdoking** [MinSikSon/idiotquant#18]
종목 리스트 lastest.json 파일 만들기

**Comment by MinSikSon** [comment]
https://github.com/MinSikSon/idiotquant/blob/feature/13-moved-execution-location-to-main/main.py
에서 작업 된 상태임.

**Comment by MinSikSon** [comment]
'오늘' 기준으로 latest.json 파일 생성되도록 하는 것도 https://github.com/MinSikSon/idiotquant/blob/feature/13-moved-execution-location-to-main/main.py 에서 작업함.
