### ISSUE TITLE
누락된 키 넣기

### ISSUE THREAD

**Issue by ohdoking** [MinSikSon/idiotquant#21]
누락된 키 넣기 in lastest.json

ex) 종목명

**Comment by MinSikSon** [comment]
https://github.com/MinSikSon/idiotquant/pull/24 리뷰 해주세염.

**Comment by MinSikSon** [comment]
애초에 해당 종목에 대한 유의미한 데이터가 없는 경우에는, 그 종목에 대한 데이터 생성하지 않습니다.
이런 경우에 대한 예외처리 필요합니다(값 가져다 쓰는 쪽에서 예외처리 하는게 더 간편함)
